Add aliases for commands
Rithari/OnePlusBot pull request #50
Opened 2019-06-02 22:02 UTC by TheOddball

2019-06-02 22:08 UTC, novelhawk requested changes

2019-06-02 22:08 UTC, ITALIA195 commented on src/OnePlusBot/Modules/Ban.cs
> +        [Alias("b")]
I would not use single letter, not common abbreviations.

2019-06-02 22:08 UTC, ITALIA195 commented on src/OnePlusBot/Modules/Echo.cs
> +        [Alias("e")]
Same as above

2019-06-02 22:08 UTC, ITALIA195 commented on src/OnePlusBot/Modules/FAQ.cs
> +        [Alias("f")]
Same as above

2019-06-02 22:08 UTC, ITALIA195 commented on src/OnePlusBot/Modules/Help.cs
> +        [Alias("h")]
`h` is an uncommon abbreviations for help; I would use ? but it might create some confusion as it's often used as a bot prefix.

2019-06-02 22:08 UTC, ITALIA195 commented on src/OnePlusBot/Modules/Kick.cs
> +        [Alias("k")]
Same as other one letter aliases

2019-06-02 22:08 UTC, ITALIA195 commented on src/OnePlusBot/Modules/News.cs
> +        [Alias("n")]
Same as other one letter aliases

2019-06-02 22:08 UTC, ITALIA195 commented on src/OnePlusBot/Modules/Report.cs
> +        [Alias("r")]
Same as other one letter aliases. I suggest `rep` but might be confused for "give reputation"

2019-06-02 22:08 UTC, ITALIA195 commented on src/OnePlusBot/Modules/ShowAvatar.cs
> +        [Alias("ava")]
I'd suggest `avatar` or just replace `showavatar`

2019-06-02 22:08 UTC, ITALIA195 commented on src/OnePlusBot/Modules/UserInfo.cs
> +        [Alias("u")]
Even as single letter alias I would approve this as it's a common abbreviation.

2019-06-02 22:08 UTC, ITALIA195 commented on src/OnePlusBot/Modules/UserInfo.cs
> -        [Command("user")]
I would keep it as an alias

2019-06-02 22:08 UTC, ITALIA195 commented on src/OnePlusBot/Modules/Warning.cs
> +        [Alias("w")]
Acceptable but can be seen as `whisper`

2019-06-02 22:08 UTC, ITALIA195 commented on src/OnePlusBot/Modules/showemoji.cs
> +        [Alias("se")]
`se` does not resemble `showemotes`; I suggest `emotes`

2019-06-03 11:16 UTC, Rithari commented
I would personally still rather not have any aliases, considering the given ones.

2019-06-05 17:12 UTC, Rithari commented
Please address the requested changes asap. 
@TheOddball

2019-06-17 21:17 UTC, closed without merging